### ISSUE TITLE
FAQ Collection

### ISSUE THREAD

**Issue by michael-spengler** [cultfamily-on-github/decentralized-open-source-ai-supporting-the-cultdao#3]
For the ones who do not want to edit training data directly within this json file: https://github.com/cultfamily-on-github/decentralized-open-source-ai-supporting-the-cultdao/blob/main/src/node-nlp-server/training-data.ts

You might consider just collecting Questions and Answers as comments on this issue. 

The idea is that everyone can collect questions which you receive in the CULTDAO context and train the AI to answer it in the future. This might save you time so that you can focus on more valuable things than answering repetitive questions.

And please always check first if he can already answer your questions appropriately: https://t.me/cultmagazine_bot

**Comment by michael-spengler** [comment]
Feel free to add your Q&A pair as comment in a format like this:

Question: 

Answer: 

Question: 

Answer: 

...

**Comment by littlemanpower** [comment]
The AI isn't responding today?

**Comment by michael-spengler** [comment]
closing this issue because there is an even simpler approach available now leveraging github issue forms: 
https://github.com/cultfamily-on-github/decentralized-open-source-ai-supporting-the-cultdao/issues/new?assignees=octocat&labels=trainingdata%2Cfaq&template=q-and-a-pair.yaml&title=A+new+example+q+%26+a+pair+is+coming+to+train+the+CULT+Beast.
